Import('env', 'arch', 'messaging', 'common', 'gpucommon', 'visionipc')

libs = ['pthread', common, visionipc, messaging, 'OpenCL', gpucommon]

if arch != "Darwin":
  camera_obj = env.Object(['cameras/camera_qcom2.cc', 'cameras/camera_common.cc', 'cameras/spectra.cc',
                           'cameras/cdm.cc', 'sensors/ar0231.cc', 'sensors/ox03c10.cc', 'sensors/os04c10.cc',
                           'cameras/mipi/camera_mipi.cc', 'cameras/mipi/mipi_utils.cc',
                           'cameras/usb/camera_usb.cc'])
  env.Program('camerad', ['main.cc', 'camerad_thread.cc', camera_obj], LIBS=libs + ['yuv', 'jpeg'])

if GetOption("extras") and arch == "x86_64":
  env.Program('test/test_ae_gray', ['test/test_ae_gray.cc', camera_obj], LIBS=libs + ['yuv', 'jpeg'])
