Import('env', 'arch', 'messaging', 'common', 'visionipc')

libs = [common, messaging, visionipc, "turbojpeg", "avformat", "avcodec", "avutil", "swscale", "x264", "z", "m", "pthread"]
#sudo apt install -y libturbojpeg0-dev

if arch == "x86_64":
  camera_obj = env.Object([ 'camera.cc', 'camerad.cc'])
  env.Program('camerad', ['main.cc', camera_obj], LIBS=libs)
