Import('env', 'arch', 'messaging', 'common', 'visionipc')

# gpucommon is not defined in this build, use OpenCL directly
libs = [common, 'OpenCL', messaging, visionipc, "turbojpeg", "avformat", "avcodec", "avutil", "swscale", "z", "x264"]
#sudo apt install -y libturbojpeg0-dev

if arch == "x86_64":
  camera_obj = env.Object([ 'camera.cc', 'camerad.cc'])
  env.Program('camerad', ['main.cc', camera_obj], LIBS=libs)
