Import('qt_env', 'arch', 'common', 'messaging', 'visionipc', 'transformations', 'widgets', 'qt_util', 'qt_libs')

base_libs = [common, messaging, visionipc, transformations,
             'm', 'OpenCL', 'ssl', 'crypto', 'pthread', 'OmxCore', 'avformat', 'avcodec', 'avutil', 'yuv'] + qt_env["LIBS"]

if arch == 'larch64':
  base_libs.append('EGL')

maps = arch in ['larch64', 'aarch64', 'x86_64']

if arch == "Darwin":
  del base_libs[base_libs.index('OpenCL')]
  qt_env['FRAMEWORKS'] += ['OpenCL']

# FIXME: remove this once we're on 5.15 (24.04)
qt_env['CXXFLAGS'] += ["-Wno-deprecated-declarations"]

sp_widgets_src = [
  "sunnypilot/qt/widgets/controls.cc",
  "sunnypilot/qt/widgets/toggle.cc",
]

sp_qt_src = [
  "sunnypilot/qt/offroad/settings/spp_settings_panel.cc",
]

sp_widgets = qt_env.Library("sp_widgets", sp_widgets_src, LIBS=base_libs)
sp_qt = qt_env.Library("sp_qt", sp_qt_src, LIBS=base_libs + [widgets, qt_util])

Export('sp_widgets', 'sp_qt')